### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hbowden** [AlexDenisov/segment_dumper#1]
I'm currently using some of your segment_dumper code in a project of mine: https://github.com/2trill2spill/nextgen . First I would like to thank you for your tutorial/article: http://lowlevelbits.org/parsing-mach-o-files/, It was the most clear article/info I found on parsing mach-o files.

What license is this example released under? I want to make sure the license is compatible with my project and I want to add the license to the code I'm using from  segment_dumper so people know it's your code and copyright.

Thanks and have a good day,
Harrison

**Comment by AlexDenisov** [comment]
Thank you for your kind words, @2trill2spill.
I just added MIT license, please let me know if it works for you or not.

**Comment by hbowden** [comment]
The MIT license will work great and thanks again!
